---
- name: Update packages on RHEL system
  hosts: all

  tasks:

    - name: perform yum update
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*
      async: 1000
      poll: 0
      register: yum_sleeper

    - name: 'YUM - check on async task'
      async_status:
        jid: "{{ yum_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
