---
- name: Update packages on RHEL system
  hosts: all

  tasks:

    - name: perform yum update
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*
      register: yum_output

    - debug: var=yum_output
